### ISSUE TITLE
the role 'provision/local' was not found

### ISSUE THREAD

**Issue by jkilpatr** [redhat-openstack/ci-ansible-tripleo#2]
ERROR! the role 'provision/local' was not found in /root/ci-ansible-tripleo/.cat/playbooks/roles:/root/ci-ansible-tripleo/.cat/playbooks:/usr/lib/python2.7/site-packages/tripleo-quickstart/playbooks/roles:/root/ci-ansible-tripleo/.cat/usr/local/share/tripleo-quickstart/roles:/root/ci-ansible-tripleo/.cat/usr/local/share

The error appears to have been in '/root/ci-ansible-tripleo/.cat/playbooks/provision.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - provision/local
      ^ here

I've been trying to use CAT for a couple of days now and I keep running into this error. I have seen deployments of CAT that don't seem to encounter the problem but there doesn't seem to be any documentation here that would account for the difference.

**Comment by Toure** [comment]
jkilpatr what deployment command are you using?

**Comment by jkilpatr** [comment]
Tried it with and without the -c, the result is the same.

./deploy.sh -c MyTestBox

**Comment by Toure** [comment]
Try running it as a non-root user. Also this project is being merged into tripleO-quickstart.
https://github.com/openstack/tripleo-quickstart

**Comment by jkilpatr** [comment]
Non-root seems to do the trick, sorry for the trouble.
